apiVersion: acme.com/v1
kind: Workload
metadata:
  name: api
route: /kblocks/api(/|$)(.*)
rewrite: /$2
image: wingcloudbot/kblocks-ui-api:sha-{{ .Values.revision }}
replicas: 1
port: 3000
env:
  PORT: "3000"
  KBLOCKS_GROUP_NAME: acme.com
  KBLOCKS_NAMESPACE: acme-operators
  KBLOCKS_CONFIG_MAP_ANNOTATION: kblocks.io/docs
command: ["pnpm", "run", "dev"]
allow:
  - apiVersion: apiextensions.k8s.io
    resource: customresourcedefinitions
    verbs: ["get", "list", "watch"]
  - apiVersion: v1
    resource: configmaps
    verbs: ["get", "list", "watch"]
  - apiVersion: v1
    resource: secrets
    verbs: ["get", "list", "watch"]
  - apiVersion: argoproj.io/v1alpha1
    resource: applications
    verbs: ["get", "list", "watch"]
  - apiVersion: acme.com/v1
    resource: "*"
    verbs: ["get", "list", "watch"]
